lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
