name: Siemens Mobile Dev
title: null
source: .
highlighter: rouge
kramdown:
  input: GFM
theme: just-the-docs

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
